### ISSUE TITLE
Pb with wheatley on Mac: device not recognized

### ISSUE THREAD

**Issue by galleon** [jolibrain/wheatley#91]
**OS:** OSX 14.1.1 (23B2082)

**Packages:**
```
Package              Version
-------------------- ------------
absl-py              2.0.0
certifi              2023.11.17
charset-normalizer   3.3.2
cloudpickle          3.0.0
contourpy            1.2.0
cycler               0.12.1
dgl                  1.1.2.post1
einops               0.7.0
Farama-Notifications 0.0.4
filelock             3.13.1
fonttools            4.45.0
fsspec               2023.10.0
gymnasium            0.29.1
idna                 3.4
Jinja2               3.1.2
jsonpatch            1.33
jsonpointer          2.4
kaleido              0.2.1
kiwisolver           1.4.5
MarkupSafe           2.1.3
matplotlib           3.8.2
mpmath               1.3.0
networkx             3.2.1
numpy                1.26.2
opencv-python        4.8.1.78
ortools              9.8.3296
packaging            23.2
pandas               2.1.3
Pillow               10.1.0
pip                  23.3.1
plotly               5.18.0
pre                  1.3.0
protobuf             4.25.1
psutil               5.9.6
pyparsing            3.1.1
python-dateutil      2.8.2
pytz                 2023.3.post1
requests             2.31.0
scipy                1.11.4
setuptools           65.5.0
six                  1.16.0
sympy                1.12
tenacity             8.2.3
torch                2.1.1
torchinfo            1.8.0
tornado              6.3.3
tqdm                 4.66.1
typing_extensions    4.8.0
tzdata               2023.3
urllib3              2.1.0
visdom               0.2.4
websocket-client     1.6.4
```

DGL installed using: `pip install dgl -f https://data.dgl.ai/wheels/repo.html`

```
...
│    │    └─Linear: 3-29                 [1, 18, 1]                925
==========================================================================================
Total params: 2,185,664
Trainable params: 2,185,664
Non-trainable params: 0
Total mult-adds (Units.MEGABYTES): 146.25
==========================================================================================
Input size (MB): 0.00
Forward/backward pass size (MB): 6.50
Params size (MB): 8.73
Estimated Total Size (MB): 15.24
==========================================================================================
initial validation

   evaluating         :   0%|          | 0/1 [00:00<?, ?it/s]
   evaluating         :   0%|          | 0/1 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "/Users/alleon_g/code/wheatley/psp/train_psp.py", line 282, in <module>
    main(args, exp_name, path)
  File "/Users/alleon_g/code/wheatley/psp/train_psp.py", line 262, in main
    return ppo.train(
           ^^^^^^^^^^
  File "/Users/alleon_g/code/wheatley/alg/ppo.py", line 366, in train
    self.validator.validate(agent, self)
  File "/Users/alleon_g/code/wheatley/generic/agent_validator.py", line 244, in validate
    self._evaluate_agent(agent)
  File "/Users/alleon_g/code/wheatley/generic/agent_validator.py", line 430, in _evaluate_agent
    action = agent.predict(
             ^^^^^^^^^^^^^^
  File "/Users/alleon_g/code/wheatley/generic/agent.py", line 145, in predict
    features = self.gnn(observation)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/alleon_g/.pyenv/versions/wheatley/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/alleon_g/.pyenv/versions/wheatley/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/alleon_g/code/wheatley/psp/models/gnn_dgl.py", line 301, in forward
    g = g.to(next(self.parameters()).device)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/alleon_g/.pyenv/versions/wheatley/lib/python3.11/site-packages/dgl/heterograph.py", line 5709, in to
    ret._graph = self._graph.copy_to(utils.to_dgl_context(device))
                                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/alleon_g/.pyenv/versions/wheatley/lib/python3.11/site-packages/dgl/utils/internal.py", line 585, in to_dgl_context
    device_type = nd.DGLContext.STR2MASK[F.device_type(ctx)]
                  ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^
KeyError: 'mps'

```

**Comment by beniz** [comment]
https://github.com/dmlc/dgl/blob/34da58da3c2d4a54bd1635f05d1491724e4c335f/python/dgl/_ffi/runtime_ctypes.py#L130 DGLContext has not support for `mps` is seems

**Comment by beniz** [comment]
There's no true support of `mps` within DGL, https://github.com/dmlc/dgl/issues/4725#issuecomment-1546282610

**Comment by beniz** [comment]
run with `--device cpu`  instead.
